# Autogenerated wrapper script for HHsuite_jll for aarch64-linux-musl-cxx11
export a3m_database_extract, a3m_database_filter, a3m_database_reduce, a3m_extract, a3m_reduce, cstranslate, ffindex_apply, ffindex_build, ffindex_from_fasta, ffindex_from_fasta_with_split, ffindex_get, ffindex_modify, ffindex_order, ffindex_reduce, ffindex_unpack, hhalign, hhalign_omp, hhblits, hhblits_ca3m, hhblits_omp, hhconsensus, hhfilter, hhmake, hhsearch, hhsearch_omp

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("HHsuite")
JLLWrappers.@declare_executable_product(a3m_database_extract)
JLLWrappers.@declare_executable_product(a3m_database_filter)
JLLWrappers.@declare_executable_product(a3m_database_reduce)
JLLWrappers.@declare_executable_product(a3m_extract)
JLLWrappers.@declare_executable_product(a3m_reduce)
JLLWrappers.@declare_executable_product(cstranslate)
JLLWrappers.@declare_executable_product(ffindex_apply)
JLLWrappers.@declare_executable_product(ffindex_build)
JLLWrappers.@declare_executable_product(ffindex_from_fasta)
JLLWrappers.@declare_executable_product(ffindex_from_fasta_with_split)
JLLWrappers.@declare_executable_product(ffindex_get)
JLLWrappers.@declare_executable_product(ffindex_modify)
JLLWrappers.@declare_executable_product(ffindex_order)
JLLWrappers.@declare_executable_product(ffindex_reduce)
JLLWrappers.@declare_executable_product(ffindex_unpack)
JLLWrappers.@declare_executable_product(hhalign)
JLLWrappers.@declare_executable_product(hhalign_omp)
JLLWrappers.@declare_executable_product(hhblits)
JLLWrappers.@declare_executable_product(hhblits_ca3m)
JLLWrappers.@declare_executable_product(hhblits_omp)
JLLWrappers.@declare_executable_product(hhconsensus)
JLLWrappers.@declare_executable_product(hhfilter)
JLLWrappers.@declare_executable_product(hhmake)
JLLWrappers.@declare_executable_product(hhsearch)
JLLWrappers.@declare_executable_product(hhsearch_omp)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        a3m_database_extract,
        "bin/a3m_database_extract",
    )

    JLLWrappers.@init_executable_product(
        a3m_database_filter,
        "bin/a3m_database_filter",
    )

    JLLWrappers.@init_executable_product(
        a3m_database_reduce,
        "bin/a3m_database_reduce",
    )

    JLLWrappers.@init_executable_product(
        a3m_extract,
        "bin/a3m_extract",
    )

    JLLWrappers.@init_executable_product(
        a3m_reduce,
        "bin/a3m_reduce",
    )

    JLLWrappers.@init_executable_product(
        cstranslate,
        "bin/cstranslate",
    )

    JLLWrappers.@init_executable_product(
        ffindex_apply,
        "bin/ffindex_apply",
    )

    JLLWrappers.@init_executable_product(
        ffindex_build,
        "bin/ffindex_build",
    )

    JLLWrappers.@init_executable_product(
        ffindex_from_fasta,
        "bin/ffindex_from_fasta",
    )

    JLLWrappers.@init_executable_product(
        ffindex_from_fasta_with_split,
        "bin/ffindex_from_fasta_with_split",
    )

    JLLWrappers.@init_executable_product(
        ffindex_get,
        "bin/ffindex_get",
    )

    JLLWrappers.@init_executable_product(
        ffindex_modify,
        "bin/ffindex_modify",
    )

    JLLWrappers.@init_executable_product(
        ffindex_order,
        "bin/ffindex_order",
    )

    JLLWrappers.@init_executable_product(
        ffindex_reduce,
        "bin/ffindex_reduce",
    )

    JLLWrappers.@init_executable_product(
        ffindex_unpack,
        "bin/ffindex_unpack",
    )

    JLLWrappers.@init_executable_product(
        hhalign,
        "bin/hhalign",
    )

    JLLWrappers.@init_executable_product(
        hhalign_omp,
        "bin/hhalign_omp",
    )

    JLLWrappers.@init_executable_product(
        hhblits,
        "bin/hhblits",
    )

    JLLWrappers.@init_executable_product(
        hhblits_ca3m,
        "bin/hhblits_ca3m",
    )

    JLLWrappers.@init_executable_product(
        hhblits_omp,
        "bin/hhblits_omp",
    )

    JLLWrappers.@init_executable_product(
        hhconsensus,
        "bin/hhconsensus",
    )

    JLLWrappers.@init_executable_product(
        hhfilter,
        "bin/hhfilter",
    )

    JLLWrappers.@init_executable_product(
        hhmake,
        "bin/hhmake",
    )

    JLLWrappers.@init_executable_product(
        hhsearch,
        "bin/hhsearch",
    )

    JLLWrappers.@init_executable_product(
        hhsearch_omp,
        "bin/hhsearch_omp",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
